include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - ios/**
    - android/**
    - linux/**
    - macos/**
    - web/**
    - windows/**
    - .dart_tool/**
    - lib/generated/**

linter:
  rules:
    constant_identifier_names: false