name: project_shelf_v3
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  intl: any
  go_router: ^16.1.0
  path_provider: ^2.1.5
  flutter_svg: ^2.2.0
  path: ^1.9.1
  logger: ^2.6.1
  json_annotation: ^4.9.0
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  freezed_annotation: ^3.1.0
  money2: ^6.0.5
  csv: ^6.0.0
  shared_preferences: ^2.5.3
  objectbox: any
  objectbox_flutter_libs: any
  get_it: ^8.2.0
  image_picker: ^1.2.0
  package_info_plus: ^9.0.0
  jiffy: ^6.4.3
  rxdart: ^0.28.0
  uuid: ^4.5.1
  esc_pos_utils_plus: ^2.0.4
  print_bluetooth_thermal: ^1.1.6
  image: ^4.5.4
  diacritic: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: any
  custom_lint: any
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17
  objectbox_generator: any
  drift_dev: ^2.28.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  faker: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/raw/departments_cities.csv
    - assets/static/currenciesInfo.json
    - assets/img/default_logo.jpeg
