name: project_shelf_v3
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.0+3

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  intl: any
  go_router: ^16.1.0
  path_provider: ^2.1.5
  flutter_svg: ^2.2.0
  path: ^1.9.1
  logger: ^2.6.1
  json_annotation: ^4.9.0
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  freezed_annotation: ^3.1.0
  money2: ^6.0.5
  csv: ^6.0.0
  shared_preferences: ^2.5.3
  objectbox: any
  objectbox_flutter_libs: any
  get_it: ^8.2.0
  injectable: ^2.5.2
  image_picker: ^1.2.0
  package_info_plus: ^9.0.0
  jiffy: ^6.4.3
  rxdart: ^0.28.0
  uuid: ^4.5.1
  esc_pos_utils_plus: ^2.0.4
  print_bluetooth_thermal: ^1.1.6
  image: ^4.5.4
  diacritic: ^0.1.6
  file_picker: ^10.3.3
  oxidized: ^6.2.0
  sqflite: ^2.4.2
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: any
  build_runner: any
  custom_lint: any
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17
  objectbox_generator: any
  drift_dev: ^2.28.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  faker: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/raw/departments_cities.csv
    - assets/static/currenciesInfo.json
    - assets/img/default_logo.jpeg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/default_logo.jpeg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/img/default_logo.jpeg"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/img/default_logo.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/img/default_logo.jpeg"
