name: project_shelf_v3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  flutter_localizations:
    sdk: flutter
  intl: any
  go_router: ^16.1.0
  path_provider: ^2.1.5
  flutter_svg: ^2.2.0
  path: ^1.9.1
  logger: ^2.6.1
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.1
  drift: ^2.28.1
  drift_flutter: ^0.2.5
  freezed_annotation: ^3.1.0
  money2: ^6.0.5
  csv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: 
  custom_lint: 
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17
  drift_dev: ^2.28.1
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/raw/departments_citiens.csv